apiVersion: v1
kind: Service
metadata:
  name: spring-test-service
spec:
  selector:
    app: spring-test-app
  ports:
    - port: 8085
      protocol: "TCP"
      targetPort: 8081
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-test-app
spec:
  selector:
    matchLabels:
      app: spring-test-app
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-test-app
    spec:
      containers:
        - name: spring-test-app
          image: spring-argo-test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
